server:
  port: 8080

spring:
  datasource:
    username: root
    password: pyh903903
    url: jdbc:mysql://120.77.13.126:3306/platform?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:3306/platform?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  web:
    resources:
      static-locations: classpath:/static/



#mybatis:
#  mapper-locations: classpath:mybatis\mapper\*.xml
mybatis:
  #mapper-locations: classpath:hchier\springboot\mapper\*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #输出sql到控制台
    map-underscore-to-camel-case: true